# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'SphereViewer.ui'
#
# Created by: PyQt5 UI code generator 5.13.0
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(824, 702)
        font = QtGui.QFont()
        font.setPointSize(12)
        MainWindow.setFont(font)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.centralwidget.sizePolicy().hasHeightForWidth())
        self.centralwidget.setSizePolicy(sizePolicy)
        self.centralwidget.setAcceptDrops(False)
        self.centralwidget.setAutoFillBackground(False)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.gridLayout_2 = QtWidgets.QGridLayout()
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.label0_5 = QtWidgets.QLabel(self.centralwidget)
        self.label0_5.setAutoFillBackground(False)
        self.label0_5.setStyleSheet("background-color: black")
        self.label0_5.setText("")
        self.label0_5.setObjectName("label0_5")
        self.gridLayout_2.addWidget(self.label0_5, 0, 5, 1, 1)
        self.label2_1 = QtWidgets.QLabel(self.centralwidget)
        self.label2_1.setAutoFillBackground(False)
        self.label2_1.setStyleSheet("background-color: black")
        self.label2_1.setText("")
        self.label2_1.setObjectName("label2_1")
        self.gridLayout_2.addWidget(self.label2_1, 2, 1, 1, 1)
        self.label3_1 = QtWidgets.QLabel(self.centralwidget)
        self.label3_1.setAutoFillBackground(False)
        self.label3_1.setStyleSheet("background-color: black")
        self.label3_1.setText("")
        self.label3_1.setObjectName("label3_1")
        self.gridLayout_2.addWidget(self.label3_1, 3, 1, 1, 1)
        self.label0_0 = QtWidgets.QLabel(self.centralwidget)
        self.label0_0.setAutoFillBackground(False)
        self.label0_0.setStyleSheet("background-color: black")
        self.label0_0.setText("")
        self.label0_0.setObjectName("label0_0")
        self.gridLayout_2.addWidget(self.label0_0, 0, 0, 1, 1)
        self.label3_4 = QtWidgets.QLabel(self.centralwidget)
        self.label3_4.setAutoFillBackground(False)
        self.label3_4.setStyleSheet("background-color: black")
        self.label3_4.setText("")
        self.label3_4.setObjectName("label3_4")
        self.gridLayout_2.addWidget(self.label3_4, 3, 4, 1, 1)
        self.label4_1 = QtWidgets.QLabel(self.centralwidget)
        self.label4_1.setAutoFillBackground(False)
        self.label4_1.setStyleSheet("background-color: black")
        self.label4_1.setText("")
        self.label4_1.setObjectName("label4_1")
        self.gridLayout_2.addWidget(self.label4_1, 4, 1, 1, 1)
        self.label2_8 = QtWidgets.QLabel(self.centralwidget)
        self.label2_8.setAutoFillBackground(False)
        self.label2_8.setStyleSheet("background-color: black")
        self.label2_8.setText("")
        self.label2_8.setObjectName("label2_8")
        self.gridLayout_2.addWidget(self.label2_8, 2, 8, 1, 1)
        self.label4_6 = QtWidgets.QLabel(self.centralwidget)
        self.label4_6.setAutoFillBackground(False)
        self.label4_6.setStyleSheet("background-color: black")
        self.label4_6.setText("")
        self.label4_6.setObjectName("label4_6")
        self.gridLayout_2.addWidget(self.label4_6, 4, 6, 1, 1)
        self.label3_0 = QtWidgets.QLabel(self.centralwidget)
        self.label3_0.setAutoFillBackground(False)
        self.label3_0.setStyleSheet("background-color: black")
        self.label3_0.setText("")
        self.label3_0.setObjectName("label3_0")
        self.gridLayout_2.addWidget(self.label3_0, 3, 0, 1, 1)
        self.label0_8 = QtWidgets.QLabel(self.centralwidget)
        self.label0_8.setAutoFillBackground(False)
        self.label0_8.setStyleSheet("background-color: black")
        self.label0_8.setText("")
        self.label0_8.setObjectName("label0_8")
        self.gridLayout_2.addWidget(self.label0_8, 0, 8, 1, 1)
        self.label1_2 = QtWidgets.QLabel(self.centralwidget)
        self.label1_2.setAutoFillBackground(False)
        self.label1_2.setStyleSheet("background-color: black")
        self.label1_2.setText("")
        self.label1_2.setObjectName("label1_2")
        self.gridLayout_2.addWidget(self.label1_2, 1, 2, 1, 1)
        self.label0_3 = QtWidgets.QLabel(self.centralwidget)
        self.label0_3.setAutoFillBackground(False)
        self.label0_3.setStyleSheet("background-color: black")
        self.label0_3.setText("")
        self.label0_3.setObjectName("label0_3")
        self.gridLayout_2.addWidget(self.label0_3, 0, 3, 1, 1)
        self.label4_0 = QtWidgets.QLabel(self.centralwidget)
        self.label4_0.setAutoFillBackground(False)
        self.label4_0.setStyleSheet("background-color: black")
        self.label4_0.setText("")
        self.label4_0.setObjectName("label4_0")
        self.gridLayout_2.addWidget(self.label4_0, 4, 0, 1, 1)
        self.label4_3 = QtWidgets.QLabel(self.centralwidget)
        self.label4_3.setAutoFillBackground(False)
        self.label4_3.setStyleSheet("background-color: black")
        self.label4_3.setText("")
        self.label4_3.setObjectName("label4_3")
        self.gridLayout_2.addWidget(self.label4_3, 4, 3, 1, 1)
        self.label2_0 = QtWidgets.QLabel(self.centralwidget)
        self.label2_0.setAutoFillBackground(False)
        self.label2_0.setStyleSheet("background-color: black")
        self.label2_0.setText("")
        self.label2_0.setObjectName("label2_0")
        self.gridLayout_2.addWidget(self.label2_0, 2, 0, 1, 1)
        self.label3_5 = QtWidgets.QLabel(self.centralwidget)
        self.label3_5.setAutoFillBackground(False)
        self.label3_5.setStyleSheet("background-color: black")
        self.label3_5.setText("")
        self.label3_5.setObjectName("label3_5")
        self.gridLayout_2.addWidget(self.label3_5, 3, 5, 1, 1)
        self.label4_7 = QtWidgets.QLabel(self.centralwidget)
        self.label4_7.setAutoFillBackground(False)
        self.label4_7.setStyleSheet("background-color: black")
        self.label4_7.setText("")
        self.label4_7.setObjectName("label4_7")
        self.gridLayout_2.addWidget(self.label4_7, 4, 7, 1, 1)
        self.label4_8 = QtWidgets.QLabel(self.centralwidget)
        self.label4_8.setAutoFillBackground(False)
        self.label4_8.setStyleSheet("background-color: black")
        self.label4_8.setText("")
        self.label4_8.setObjectName("label4_8")
        self.gridLayout_2.addWidget(self.label4_8, 4, 8, 1, 1)
        self.label5_1 = QtWidgets.QLabel(self.centralwidget)
        self.label5_1.setStyleSheet("background-color: black")
        self.label5_1.setText("")
        self.label5_1.setObjectName("label5_1")
        self.gridLayout_2.addWidget(self.label5_1, 6, 1, 1, 1)
        self.label5_4 = QtWidgets.QLabel(self.centralwidget)
        self.label5_4.setStyleSheet("background-color: black")
        self.label5_4.setText("")
        self.label5_4.setObjectName("label5_4")
        self.gridLayout_2.addWidget(self.label5_4, 6, 4, 1, 1)
        self.label5_2 = QtWidgets.QLabel(self.centralwidget)
        self.label5_2.setStyleSheet("background-color: black")
        self.label5_2.setText("")
        self.label5_2.setObjectName("label5_2")
        self.gridLayout_2.addWidget(self.label5_2, 6, 2, 1, 1)
        self.label0_4 = QtWidgets.QLabel(self.centralwidget)
        self.label0_4.setAutoFillBackground(False)
        self.label0_4.setStyleSheet("background-color: black")
        self.label0_4.setText("")
        self.label0_4.setObjectName("label0_4")
        self.gridLayout_2.addWidget(self.label0_4, 0, 4, 1, 1)
        self.label4_4 = QtWidgets.QLabel(self.centralwidget)
        self.label4_4.setAutoFillBackground(False)
        self.label4_4.setStyleSheet("background-color: black")
        self.label4_4.setText("")
        self.label4_4.setObjectName("label4_4")
        self.gridLayout_2.addWidget(self.label4_4, 4, 4, 1, 1)
        self.label5_7 = QtWidgets.QLabel(self.centralwidget)
        self.label5_7.setStyleSheet("background-color: black")
        self.label5_7.setText("")
        self.label5_7.setObjectName("label5_7")
        self.gridLayout_2.addWidget(self.label5_7, 6, 7, 1, 1)
        self.label3_8 = QtWidgets.QLabel(self.centralwidget)
        self.label3_8.setAutoFillBackground(False)
        self.label3_8.setStyleSheet("background-color: black")
        self.label3_8.setText("")
        self.label3_8.setObjectName("label3_8")
        self.gridLayout_2.addWidget(self.label3_8, 3, 8, 1, 1)
        self.label2_7 = QtWidgets.QLabel(self.centralwidget)
        self.label2_7.setAutoFillBackground(False)
        self.label2_7.setStyleSheet("background-color: black")
        self.label2_7.setText("")
        self.label2_7.setObjectName("label2_7")
        self.gridLayout_2.addWidget(self.label2_7, 2, 7, 1, 1)
        self.label1_0 = QtWidgets.QLabel(self.centralwidget)
        self.label1_0.setAutoFillBackground(False)
        self.label1_0.setStyleSheet("background-color: black")
        self.label1_0.setText("")
        self.label1_0.setObjectName("label1_0")
        self.gridLayout_2.addWidget(self.label1_0, 1, 0, 1, 1)
        self.label3_6 = QtWidgets.QLabel(self.centralwidget)
        self.label3_6.setAutoFillBackground(False)
        self.label3_6.setStyleSheet("background-color: black")
        self.label3_6.setText("")
        self.label3_6.setObjectName("label3_6")
        self.gridLayout_2.addWidget(self.label3_6, 3, 6, 1, 1)
        self.label4_5 = QtWidgets.QLabel(self.centralwidget)
        self.label4_5.setAutoFillBackground(False)
        self.label4_5.setStyleSheet("background-color: black")
        self.label4_5.setText("")
        self.label4_5.setObjectName("label4_5")
        self.gridLayout_2.addWidget(self.label4_5, 4, 5, 1, 1)
        self.label1_4 = QtWidgets.QLabel(self.centralwidget)
        self.label1_4.setAutoFillBackground(False)
        self.label1_4.setStyleSheet("background-color: black")
        self.label1_4.setText("")
        self.label1_4.setObjectName("label1_4")
        self.gridLayout_2.addWidget(self.label1_4, 1, 4, 1, 1)
        self.label1_7 = QtWidgets.QLabel(self.centralwidget)
        self.label1_7.setAutoFillBackground(False)
        self.label1_7.setStyleSheet("background-color: black")
        self.label1_7.setText("")
        self.label1_7.setObjectName("label1_7")
        self.gridLayout_2.addWidget(self.label1_7, 1, 7, 1, 1)
        self.label5_0 = QtWidgets.QLabel(self.centralwidget)
        self.label5_0.setStyleSheet("background-color: black")
        self.label5_0.setText("")
        self.label5_0.setObjectName("label5_0")
        self.gridLayout_2.addWidget(self.label5_0, 6, 0, 1, 1)
        self.label3_3 = QtWidgets.QLabel(self.centralwidget)
        self.label3_3.setAutoFillBackground(False)
        self.label3_3.setStyleSheet("background-color: black")
        self.label3_3.setText("")
        self.label3_3.setObjectName("label3_3")
        self.gridLayout_2.addWidget(self.label3_3, 3, 3, 1, 1)
        self.label1_3 = QtWidgets.QLabel(self.centralwidget)
        self.label1_3.setAutoFillBackground(False)
        self.label1_3.setStyleSheet("background-color: black")
        self.label1_3.setText("")
        self.label1_3.setObjectName("label1_3")
        self.gridLayout_2.addWidget(self.label1_3, 1, 3, 1, 1)
        self.label2_4 = QtWidgets.QLabel(self.centralwidget)
        self.label2_4.setAutoFillBackground(False)
        self.label2_4.setStyleSheet("background-color: black")
        self.label2_4.setText("")
        self.label2_4.setObjectName("label2_4")
        self.gridLayout_2.addWidget(self.label2_4, 2, 4, 1, 1)
        self.label2_5 = QtWidgets.QLabel(self.centralwidget)
        self.label2_5.setAutoFillBackground(False)
        self.label2_5.setStyleSheet("background-color: black")
        self.label2_5.setText("")
        self.label2_5.setObjectName("label2_5")
        self.gridLayout_2.addWidget(self.label2_5, 2, 5, 1, 1)
        self.label1_1 = QtWidgets.QLabel(self.centralwidget)
        self.label1_1.setAutoFillBackground(False)
        self.label1_1.setStyleSheet("background-color: black")
        self.label1_1.setText("")
        self.label1_1.setObjectName("label1_1")
        self.gridLayout_2.addWidget(self.label1_1, 1, 1, 1, 1)
        self.label1_8 = QtWidgets.QLabel(self.centralwidget)
        self.label1_8.setAutoFillBackground(False)
        self.label1_8.setStyleSheet("background-color: black")
        self.label1_8.setText("")
        self.label1_8.setObjectName("label1_8")
        self.gridLayout_2.addWidget(self.label1_8, 1, 8, 1, 1)
        self.label2_6 = QtWidgets.QLabel(self.centralwidget)
        self.label2_6.setAutoFillBackground(False)
        self.label2_6.setStyleSheet("background-color: black")
        self.label2_6.setText("")
        self.label2_6.setObjectName("label2_6")
        self.gridLayout_2.addWidget(self.label2_6, 2, 6, 1, 1)
        self.label5_6 = QtWidgets.QLabel(self.centralwidget)
        self.label5_6.setStyleSheet("background-color: black")
        self.label5_6.setText("")
        self.label5_6.setObjectName("label5_6")
        self.gridLayout_2.addWidget(self.label5_6, 6, 6, 1, 1)
        self.line = QtWidgets.QFrame(self.centralwidget)
        self.line.setMinimumSize(QtCore.QSize(0, 20))
        self.line.setLineWidth(0)
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.gridLayout_2.addWidget(self.line, 5, 0, 1, 1)
        self.label0_1 = QtWidgets.QLabel(self.centralwidget)
        self.label0_1.setAutoFillBackground(False)
        self.label0_1.setStyleSheet("background-color: black")
        self.label0_1.setText("")
        self.label0_1.setObjectName("label0_1")
        self.gridLayout_2.addWidget(self.label0_1, 0, 1, 1, 1)
        self.label2_2 = QtWidgets.QLabel(self.centralwidget)
        self.label2_2.setAutoFillBackground(False)
        self.label2_2.setStyleSheet("background-color: black")
        self.label2_2.setText("")
        self.label2_2.setObjectName("label2_2")
        self.gridLayout_2.addWidget(self.label2_2, 2, 2, 1, 1)
        self.label0_7 = QtWidgets.QLabel(self.centralwidget)
        self.label0_7.setAutoFillBackground(False)
        self.label0_7.setStyleSheet("background-color: black")
        self.label0_7.setText("")
        self.label0_7.setObjectName("label0_7")
        self.gridLayout_2.addWidget(self.label0_7, 0, 7, 1, 1)
        self.label4_2 = QtWidgets.QLabel(self.centralwidget)
        self.label4_2.setAutoFillBackground(False)
        self.label4_2.setStyleSheet("background-color: black")
        self.label4_2.setText("")
        self.label4_2.setObjectName("label4_2")
        self.gridLayout_2.addWidget(self.label4_2, 4, 2, 1, 1)
        self.label3_2 = QtWidgets.QLabel(self.centralwidget)
        self.label3_2.setAutoFillBackground(False)
        self.label3_2.setStyleSheet("background-color: black")
        self.label3_2.setText("")
        self.label3_2.setObjectName("label3_2")
        self.gridLayout_2.addWidget(self.label3_2, 3, 2, 1, 1)
        self.label0_2 = QtWidgets.QLabel(self.centralwidget)
        self.label0_2.setAutoFillBackground(False)
        self.label0_2.setStyleSheet("background-color: black")
        self.label0_2.setText("")
        self.label0_2.setObjectName("label0_2")
        self.gridLayout_2.addWidget(self.label0_2, 0, 2, 1, 1)
        self.label5_8 = QtWidgets.QLabel(self.centralwidget)
        self.label5_8.setStyleSheet("background-color: black")
        self.label5_8.setText("")
        self.label5_8.setObjectName("label5_8")
        self.gridLayout_2.addWidget(self.label5_8, 6, 8, 1, 1)
        self.label1_6 = QtWidgets.QLabel(self.centralwidget)
        self.label1_6.setAutoFillBackground(False)
        self.label1_6.setStyleSheet("background-color: black")
        self.label1_6.setText("")
        self.label1_6.setObjectName("label1_6")
        self.gridLayout_2.addWidget(self.label1_6, 1, 6, 1, 1)
        self.label2_3 = QtWidgets.QLabel(self.centralwidget)
        self.label2_3.setAutoFillBackground(False)
        self.label2_3.setStyleSheet("background-color: black")
        self.label2_3.setText("")
        self.label2_3.setObjectName("label2_3")
        self.gridLayout_2.addWidget(self.label2_3, 2, 3, 1, 1)
        self.label5_5 = QtWidgets.QLabel(self.centralwidget)
        self.label5_5.setStyleSheet("background-color: black")
        self.label5_5.setText("")
        self.label5_5.setObjectName("label5_5")
        self.gridLayout_2.addWidget(self.label5_5, 6, 5, 1, 1)
        self.label0_6 = QtWidgets.QLabel(self.centralwidget)
        self.label0_6.setAutoFillBackground(False)
        self.label0_6.setStyleSheet("background-color: black")
        self.label0_6.setText("")
        self.label0_6.setObjectName("label0_6")
        self.gridLayout_2.addWidget(self.label0_6, 0, 6, 1, 1)
        self.label5_3 = QtWidgets.QLabel(self.centralwidget)
        self.label5_3.setStyleSheet("background-color: black")
        self.label5_3.setText("")
        self.label5_3.setObjectName("label5_3")
        self.gridLayout_2.addWidget(self.label5_3, 6, 3, 1, 1)
        self.label3_7 = QtWidgets.QLabel(self.centralwidget)
        self.label3_7.setAutoFillBackground(False)
        self.label3_7.setStyleSheet("background-color: black")
        self.label3_7.setText("")
        self.label3_7.setObjectName("label3_7")
        self.gridLayout_2.addWidget(self.label3_7, 3, 7, 1, 1)
        self.label1_5 = QtWidgets.QLabel(self.centralwidget)
        self.label1_5.setAutoFillBackground(False)
        self.label1_5.setStyleSheet("background-color: black")
        self.label1_5.setText("")
        self.label1_5.setObjectName("label1_5")
        self.gridLayout_2.addWidget(self.label1_5, 1, 5, 1, 1)
        self.label6_0 = QtWidgets.QLabel(self.centralwidget)
        self.label6_0.setStyleSheet("background-color: black")
        self.label6_0.setText("")
        self.label6_0.setObjectName("label6_0")
        self.gridLayout_2.addWidget(self.label6_0, 7, 0, 1, 1)
        self.label6_1 = QtWidgets.QLabel(self.centralwidget)
        self.label6_1.setStyleSheet("background-color: black")
        self.label6_1.setText("")
        self.label6_1.setObjectName("label6_1")
        self.gridLayout_2.addWidget(self.label6_1, 7, 1, 1, 1)
        self.label6_2 = QtWidgets.QLabel(self.centralwidget)
        self.label6_2.setStyleSheet("background-color: black")
        self.label6_2.setText("")
        self.label6_2.setObjectName("label6_2")
        self.gridLayout_2.addWidget(self.label6_2, 7, 2, 1, 1)
        self.label6_3 = QtWidgets.QLabel(self.centralwidget)
        self.label6_3.setStyleSheet("background-color: black")
        self.label6_3.setText("")
        self.label6_3.setObjectName("label6_3")
        self.gridLayout_2.addWidget(self.label6_3, 7, 3, 1, 1)
        self.label6_4 = QtWidgets.QLabel(self.centralwidget)
        self.label6_4.setStyleSheet("background-color: black")
        self.label6_4.setText("")
        self.label6_4.setObjectName("label6_4")
        self.gridLayout_2.addWidget(self.label6_4, 7, 4, 1, 1)
        self.label6_5 = QtWidgets.QLabel(self.centralwidget)
        self.label6_5.setStyleSheet("background-color: black")
        self.label6_5.setText("")
        self.label6_5.setObjectName("label6_5")
        self.gridLayout_2.addWidget(self.label6_5, 7, 5, 1, 1)
        self.label6_6 = QtWidgets.QLabel(self.centralwidget)
        self.label6_6.setStyleSheet("background-color: black")
        self.label6_6.setText("")
        self.label6_6.setObjectName("label6_6")
        self.gridLayout_2.addWidget(self.label6_6, 7, 6, 1, 1)
        self.label6_7 = QtWidgets.QLabel(self.centralwidget)
        self.label6_7.setStyleSheet("background-color: black")
        self.label6_7.setText("")
        self.label6_7.setObjectName("label6_7")
        self.gridLayout_2.addWidget(self.label6_7, 7, 7, 1, 1)
        self.label6_8 = QtWidgets.QLabel(self.centralwidget)
        self.label6_8.setStyleSheet("background-color: black")
        self.label6_8.setText("")
        self.label6_8.setObjectName("label6_8")
        self.gridLayout_2.addWidget(self.label6_8, 7, 8, 1, 1)
        self.horizontalLayout_3.addLayout(self.gridLayout_2)
        self.verticalSlider = QtWidgets.QSlider(self.centralwidget)
        self.verticalSlider.setMinimum(1)
        self.verticalSlider.setMaximum(50)
        self.verticalSlider.setSliderPosition(25)
        self.verticalSlider.setTracking(True)
        self.verticalSlider.setOrientation(QtCore.Qt.Vertical)
        self.verticalSlider.setInvertedAppearance(False)
        self.verticalSlider.setInvertedControls(False)
        self.verticalSlider.setObjectName("verticalSlider")
        self.horizontalLayout_3.addWidget(self.verticalSlider)
        self.verticalLayout_2.addLayout(self.horizontalLayout_3)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.RoundCheckBox = QtWidgets.QCheckBox(self.centralwidget)
        self.RoundCheckBox.setObjectName("RoundCheckBox")
        self.horizontalLayout.addWidget(self.RoundCheckBox)
        self.StartStopButton = QtWidgets.QPushButton(self.centralwidget)
        self.StartStopButton.setObjectName("StartStopButton")
        self.horizontalLayout.addWidget(self.StartStopButton)
        self.ReloadButton = QtWidgets.QPushButton(self.centralwidget)
        self.ReloadButton.setObjectName("ReloadButton")
        self.horizontalLayout.addWidget(self.ReloadButton)
        self.verticalLayout_2.addLayout(self.horizontalLayout)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.RoundCheckBox.setText(_translate("MainWindow", "по кругу"))
        self.StartStopButton.setText(_translate("MainWindow", "Стоп"))
        self.ReloadButton.setText(_translate("MainWindow", "перезагрузить файл"))
